name: Visual Testing Pipeline

on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.png'
    - '**.drawio'
    - '**.xlsx'

jobs:
  setup-and-visual-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
            node-version: '12.x'
      
      - name: Use lerna
        run: npm install -g lerna
      
      - name: Bootstrap
        run: lerna bootstrap --no-ci
      
      - name: Visual Test
        run: |
          cd ./packages/web
          npm test
      
      - name: Upload test screenshots
        uses: actions/upload-artifact@v2
        with:
          name: playwright screenshots and downloads
          path: packages/web/test_results
